
services:
  db:
    image: crpi-57t10gj4eavw45nx-vpc.cn-beijing.personal.cr.aliyuncs.com/bey0nd/postgresql:latest
    container_name: db
    networks:
      - internal_network
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - "54321:5432"
    restart: always
    volumes:
      - "/root/data/postgresql:/bitnami/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: crpi-57t10gj4eavw45nx-vpc.cn-beijing.personal.cr.aliyuncs.com/bey0nd/golang:1.25.5-alpine
    container_name: go
    networks:
      - internal_network
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - GOPROXY=https://goproxy.cn,direct
    volumes:
      - "/root/data/go/shop-go:/app"
      - "/root/data/go/pkg:/go/pkg"
      - "/root/data/go/cache:/root/.cache/go-build"
    working_dir: "/app"
    command: >
      sh -c "cd /app && go build -o main . && ./main"

  nginx:
    image: crpi-57t10gj4eavw45nx-vpc.cn-beijing.personal.cr.aliyuncs.com/bey0nd/nginx:1.29.4-alpine
    container_name: nginx
    networks:
      - internal_network
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/root/data/nginx/html:/usr/share/nginx/html"
      - "/root/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  internal_network:
    driver: bridge